=== gkodinov/moxygen/test/fixtures/global-groups/xml-out/xml/index.xsd
<?xml version='1.0' encoding='utf-8' ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>

  <xsd:element name="doxygenindex" type="DoxygenType"/>

  <xsd:complexType name="DoxygenType">
    <xsd:sequence>
      <xsd:element name="compound" type="CompoundType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="version" type="xsd:string" use="required"/>
    <xsd:attribute ref="xml:lang" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="CompoundType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="member" type="MemberType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="refid" type="xsd:string" use="required"/>
    <xsd:attribute name="kind" type="CompoundKind" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="MemberType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
    </xsd:sequence>
    <xsd:attribute name="refid" type="xsd:string" use="required"/>
    <xsd:attribute name="kind" type="MemberKind" use="required"/>
  </xsd:complexType>

  <xsd:simpleType name="CompoundKind">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="class"/>
      <xsd:enumeration value="struct"/>
      <xsd:enumeration value="union"/>
      <xsd:enumeration value="interface"/>
      <xsd:enumeration value="protocol"/>
      <xsd:enumeration value="category"/>
      <xsd:enumeration value="exception"/>
      <xsd:enumeration value="file"/>
      <xsd:enumeration value="namespace"/>
      <xsd:enumeration value="group"/>
      <xsd:enumeration value="page"/>
      <xsd:enumeration value="example"/>
      <xsd:enumeration value="dir"/>
      <xsd:enumeration value="type"/>
      <xsd:enumeration value="concept"/>
      <xsd:enumeration value="module"/>
      <xsd:enumeration value="requirement"/>
      <xsd:enumeration value="requirements"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="MemberKind">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="define"/>
      <xsd:enumeration value="property"/>
      <xsd:enumeration value="event"/>
      <xsd:enumeration value="variable"/>
      <xsd:enumeration value="typedef"/>
      <xsd:enumeration value="enum"/>
      <xsd:enumeration value="enumvalue"/>
      <xsd:enumeration value="function"/>
      <xsd:enumeration value="signal"/>
      <xsd:enumeration value="prototype"/>
      <xsd:enumeration value="friend"/>
      <xsd:enumeration value="dcop"/>
      <xsd:enumeration value="slot"/>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== gkodinov/moxygen/test/fixtures/global-groups/xml-out/xml/index.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygenindex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index.xsd" version="1.17.0" xml:lang="en-US">
  <compound refid="classglobal__class" kind="class"><name>global_class</name>
    <member refid="classglobal__class_1affaae1576630cc2b03bd368e65f5bd96" kind="variable"><name>global_class_a</name></member>
  </compound>
  <compound refid="classnested__class" kind="class"><name>nested_class</name>
    <member refid="classnested__class_1aabd38de5178db924112338506f0b7607" kind="variable"><name>nested_class_a</name></member>
  </compound>
  <compound refid="global_8h" kind="file"><name>global.h</name>
    <member refid="global_8h_1ab16b63abd4589951d2edeccc54e70c3c" kind="define"><name>GDEFINE</name></member>
    <member refid="group__global__group_1ga6958e7f1a4f816ea5a9d200678619eb3" kind="define"><name>GGROUP_DEFINE</name></member>
    <member refid="global_8h_1ac14f6201995116bbf1ce58c95908abab" kind="variable"><name>global_a</name></member>
  </compound>
  <compound refid="group__global__group" kind="group"><name>global_group</name>
    <member refid="group__global__group_1ga6958e7f1a4f816ea5a9d200678619eb3" kind="define"><name>GGROUP_DEFINE</name></member>
  </compound>
  <compound refid="group__nested__group" kind="group"><name>nested_group</name>
  </compound>
  <compound refid="dir_68267d1309a1af8e8297ef4c3efbcdba" kind="dir"><name>src</name>
  </compound>
</doxygenindex>

=== gkodinov/moxygen/test/fixtures/member-kinds/xml-out/xml/index.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygenindex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index.xsd" version="1.9.8" xml:lang="en-US">
  <compound refid="classdemo_1_1Utility" kind="class"><name>demo::Utility</name>
    <member refid="classdemo_1_1Utility_1create" kind="function"><name>create</name></member>
    <member refid="classdemo_1_1Utility_1hidden" kind="function"><name>hidden</name></member>
    <member refid="classdemo_1_1Utility_1secret" kind="variable"><name>secret</name></member>
    <member refid="classdemo_1_1Utility_1globalSecret" kind="variable"><name>globalSecret</name></member>
  </compound>
  <compound refid="uniondemo_1_1Value" kind="union"><name>demo::Value</name>
    <member refid="uniondemo_1_1Value_1integer" kind="variable"><name>integer</name></member>
  </compound>
  <compound refid="namespacedemo" kind="namespace"><name>demo</name>
  </compound>
</doxygenindex>

=== gkodinov/moxygen/test/fixtures/issue-97/xml-out/xml/index.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygenindex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="index.xsd" version="1.17.0" xml:lang="en-US">
  <compound refid="g1_8h" kind="file"><name>g1.h</name>
    <member refid="g1_8h_1a4eaab29a4b95a3df43f309d4db0537f9" kind="variable"><name>a1</name></member>
    <member refid="group__g1_1ga527b7ac6552c449f7e636c7785318a4b" kind="variable"><name>g1_a1</name></member>
  </compound>
  <compound refid="p1_8dox" kind="file"><name>p1.dox</name>
  </compound>
  <compound refid="group__g1" kind="group"><name>g1</name>
    <member refid="group__g1_1ga527b7ac6552c449f7e636c7785318a4b" kind="variable"><name>g1_a1</name></member>
  </compound>
  <compound refid="dir_68267d1309a1af8e8297ef4c3efbcdba" kind="dir"><name>src</name>
  </compound>
  <compound refid="indexpage" kind="page"><name>index</name>
  </compound>
</doxygenindex>
